### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by CFlanc** [Atypicalim/chatbot#1]
I Get Undefined Error Every time i try to chat with the bot

**Comment by Atypicalim** [comment]
Maybe the MySQL database is not connected  correctly yet or something else .  You can set the LOG variable true in chatbot/Config.php file and open api.php?requestType=talk&userInput=hello in your browser . you would see what is hapeening exactly .

**Comment by CFlanc** [comment]
I am Using C9.ide For Testing this Out and I Configured the SQL Correctly In the Config File I Changed the Host and Username According to C9 Manual and then DB name to c9 
and Copied all the contents of chatbot.sql to c9 database 
But still it Does not work I might paste the Logs When I try it again

**Comment by Atypicalim** [comment]
I did not write a readme file in english yet . Maybe you should install mysql , then you should create a database named chatbot and import the chatbot.sql file in the root directory to your database . in the last , you should configure the database informations like userName , password in chatbot/Config.php file .

**Comment by Atypicalim** [comment]
ok, i see , you try it first .

**Comment by CFlanc** [comment]
Do I Also need to Edit the /chatbot/Database/Connection.php

**Comment by Atypicalim** [comment]
No you do not need to edit any file else . you visit the api.php file in browser and have a look at what is the hell is wrong with it .

**Comment by CFlanc** [comment]
https://chatbot-cflanc.c9users.io/api.php?requestType=talk&userInput=hey Now API works But Index Still Shows Undefined 

In the First Post 
api.php?requestType=talk&input=你好 - This is Why it was not working

**Comment by Atypicalim** [comment]
i am so sorry . i made a mistake and it was not responding standard json in api.php , i fixed it and updated . you can download the last update and try it again .

**Comment by Atypicalim** [comment]
ok , i fixed some problems and converted mysql to mysqli , it would be working well then .

**Comment by CFlanc** [comment]
**WORKS NOW!**

**Comment by titanheart900** [comment]
[kompasim](https://github.com/kompasim) &  [CFlanc](https://github.com/CFlanc)  please send me your source code, I will see where I made mistakes
