### ISSUE TITLE
Storing Predicates in Database 

### ISSUE THREAD

**Issue by CFlanc** [Atypicalim/chatbot#2]
Can User Names Be Saved In Database With Sessions ID's
`{"status":"success","type":"talk","message":"oh , your name is userName , i remembered it last time ...","data":[]}`
And What is that `data:`  Used For

**Comment by Atypicalim** [comment]
at this time userNmae will be saved in property table in database .
Then , the data : is used for send some message for api when you need to it , you can add `<data name="myArr"><attr name="arg1">value1</attr><attr name="arg2">value2</attr></data>` tag in category tag , to get a array like `"data":["arr":["arg1":"value1","arg2":"value2"]]` , you can use it when you need .

**Comment by CFlanc** [comment]
ok seems like `data:` will be very usefull atleast for me

**Comment by kompasim** [comment]
I updated it.
https://github.com/kompasim/chatbot/blob/master/README.md
