### ISSUE TITLE
system 标签无法使用

### ISSUE THREAD

**Issue by osdebianly** [Atypicalim/chatbot#3]
dame.aiml 有一段注释
```
        4：think,system tag: 支持简单逻辑记忆及自定义函数(本来打算扩展一下AIML, 搞一个支持Groovy语言的标签， 结果看到了它的<system>标签， 遂作罢)

```
增加的规则

```xml
<category>
        <pattern>TIME</pattern>
        <template>
            <system>date</system>
        </template>
</category>
```
* 返回：'date‘ 字符串   
* 期望返回： linux 命令 `date` 返回结果

**Comment by Atypicalim** [comment]
system 标签确实用来执行里面的字符串代码的，在system 标签的解析函数里面可以直接用eval()函数执行标签的nodeValue，不过这样下来会有安全问题。当你允许用户上传自己的aiml文件的时候用户会用system 执行系统有关的函数，会删除你服务器上的文件，所以我觉得没必要实现就没实现的。上次也有网友提过这个标签，不知道是不是也是你，要是觉得你需要这个标签可以在chatbot/Parser.php文件里实现相关功能扩展一下，你模仿里面的parseGet,parseStar 之类的函数很容易实现。如果希望我实现这个功能只能等一段时间了，最近有点忙不过来。

**Comment by osdebianly** [comment]
我照着加上了  [pull](https://github.com/kompasim/chatbot/pull/4)

**Comment by Atypicalim** [comment]
谢谢，我merge了你的代码，然后把exec改成eval了，我们只是会需要调用系统函数来扩展功能，而不是执行系统命令。

**Comment by Atypicalim** [comment]
例如获取系统时间。
```xml
<category>
    <pattern>system</pattern>
    <template>
        <system>
            date_default_timezone_set('PRC');
            return date('Y/m/d H:i:s');
        </system>
    </template>
</category>
```
