### ISSUE TITLE
condition

### ISSUE THREAD

**Issue by krisantoabi** [Atypicalim/chatbot#5]
![condition](https://user-images.githubusercontent.com/64880650/81135455-73d3c400-8f82-11ea-9fde-d6a952f975d5.JPG)
hi, my name is abi. I want to ask question.

- how to use tag condition, and topic in file. aiml ? 
when i,m run the bot, tag aiml topic and condition can't run .
when i said selamat pagi. bot response is pagi siang malam.

- how to make a new line or function br in file.aiml ?

- how to make a tag button in file.aiml ?

- how to make a tag img or image in file.aiml ?

- what the different type "user" and type="bot"?

sorry, if my english language is bad.

Thank You.

**Comment by Atypicalim** [comment]
just check [demo.aiml](https://github.com/kompasim/chatbot/blob/master/aiml/demo/demo.aiml) to more information about usage.
