### ISSUE TITLE
关于aiml编辑器

### ISSUE THREAD

**Issue by xkungfu** [Atypicalim/chatbot#6]
请问，如何快速批量的编辑aiml词条和文件？
外网有很多可以下载的aiml编辑，比如GaitoBot AIML editor、Simple AIML Editor等，是否适合编辑您的经过修改的aiml格式的文件？
您是否有计划开发一个aiml编辑器？
或者是否有其他更合适的方法编辑aiml文件？

**Comment by Atypicalim** [comment]
由于工作原因暂时没有开发编辑器或转化工具的计划，而且基于aiml的机器人现在只适合一些人工客服自动回复之类的使用场景，想做一个用了聊天的机器人感觉还是弱了，貌似现在都是用机器学习之类的在搞。当时开发这个只是为了实现一个php版本，所以也没有留意编辑器的格式。不过差不多都是标准的aiml语法，那些编辑器应该可以编辑的，如果有问题可以改改我们这边的php脚本内容。
