### ISSUE TITLE
xss vulnerability ?

### ISSUE THREAD

**Issue by andre0ani** [Atypicalim/chatbot#7]
It seems there's a XSS vulnerability ?
<script>alert("faille XSS");</script> show the alert message.
Could you do something please ?
Or show me how to correct this ?

Thanks for your work.

**Comment by Atypicalim** [comment]
Hello, I didn't understand your purpose to achieve. first of all, only the user input and chatbot output can be customized, I mean the input and output of `$chatbot->talk` function. so you can filter special characters or html tags at line 42 or 43 of `api.php` file, [strip_tags](https://www.php.net/manual/en/function.strip-tags.php) may be needed to filter html tags. If I didn't make it clear, further discussion is welcome, good luck for you.

**Comment by andre0ani** [comment]
Hello,
Thanks for your response and excuse me if I'm not clear.
Is there a XSS vulnerability on the form ? Please look at the screenshot, perhaps it's more clear.
I'm trying to use INPUT_FILTER to sanitize what the user put on the form to protect it but it's not working (I'm a beginner).
Thanks again for your help ;-)
![bot1](https://user-images.githubusercontent.com/101861190/189269143-08186e56-6ea5-4394-bcd0-fce714ffcc2e.png)
![bot2](https://user-images.githubusercontent.com/101861190/189269150-b4186732-9c55-4cf0-96e0-754b49f511c9.png)

I'm using your code to make a bot to talk about free software, I've made some little modification on the design of the bot, I'm not good enought to modify the code itself.
https://tuxbot.andre-ani.fr/
https://gitlab.com/andre0ani1/tuxbot

**Comment by Atypicalim** [comment]
Just search and change `text.html('\t' + message);` to `text.text('\t' + message);` in your js code, The content will be parsed as html code while using jquery [html](https://api.jquery.com/html/) method.

**Comment by andre0ani** [comment]
Thanks a lot ;-)
Have a nice day.
