### ISSUE TITLE
Date fields not parsing

### ISSUE THREAD

**Issue by carlosjm0325** [Atypicalim/chatbot#8]
Thank you so much for the contribution, this is fantastic!! I do have a problem however where date fields are not parsing (<date format="%Y"/>). - Is there any way you could provide an example on how to implement? I've tried using the example shown (pasting into "date.aiml" and am not getting any response. Any suggestions?

```
<category>
    <pattern>system</pattern>
    <template>
        <system>
            date_default_timezone_set('PRC');
            return date('Y/m/d H:i:s');
        </system>
    </template>
</category> 

```

**Comment by Atypicalim** [comment]
Sorry for my late reply, I have already fixed the `system` tag no-response issure, please update to the latest master branch and try it again, you can have a look at the commit log of the `Parser.php` if you are interested in this issure.
