### ISSUE TITLE
Undefined chatbot reply

### ISSUE THREAD

**Issue by iqbalramadhanofficial** [Atypicalim/chatbot#9]
![Screenshot_26](https://github.com/kompasim/chatbot/assets/49395900/7aa867f3-d215-4da3-b626-90fe27869fd5)
![Screenshot_27](https://github.com/kompasim/chatbot/assets/49395900/5b6a0475-2349-4ffe-b739-e882cf52b0ee)
![Screenshot_28](https://github.com/kompasim/chatbot/assets/49395900/11239882-2cd1-4eb4-a1ce-e3f542ee59cd)

Hello, can you help me with this case?

i still get undefined reply on index.php. when i check the : "api.php?requestType=talk&userInput=hello" the log worked well and give aiml responses. But when i check "api.php", the log say Undefined array key "requestType".

on "api.php" file, there no "requestType" in array. when i add the "requestType" in array, its still not worked.

thanks for help

**Comment by Atypicalim** [comment]
1. if you want to try the gui interface just open `index.php`.
2. `api.php` is for a programmatic usage, for example you want to integrate this chatbot to your own application, then you can use a http lib and reqeust `api.php`.

**Comment by Atypicalim** [comment]
3. to use `api.php` correctly , you need to add parameter `requestType`, which is supprting `chat` and `forget` two types.
4. and when you send chat for `requestType`, you also need parameter `userInput` to tell chatbot your question.

**Comment by Atypicalim** [comment]
a simple usage of api is: `/api.php?requestType=talk&userInput=hello`, in this url you are requesting for chat, and you say hello to chatbot. and the output is a json which you can decode in your own application and show in your own ui.

**Comment by iqbalramadhanofficial** [comment]
> 1. if you want to try the gui interface just open `index.php`.
> 2. `api.php` is for a programmatic usage, for example you want to integrate this chatbot to your own application, then you can use a http lib and reqeust `api.php`.



Yes, i want try the gui interface and opened index,php. But when input the chat like your screenshot file. 

like "hello" or "wow", i still get undefined result. the database name is already set in the config file.

**Comment by Atypicalim** [comment]
I see, you need to set the log variable in config.php to false, it is for debug purpose, and would print some extra informations, and this will let front end js got non-json data.

**Comment by Atypicalim** [comment]
when you check api.php directly in bowser and wanna see what is going on with the chatbot application, you can set `$log = false;` to see more log.

**Comment by Atypicalim** [comment]
![image](https://github.com/kompasim/chatbot/assets/16191037/372e64c1-720d-4509-9965-ad62b22eb6e4)
like this.
